/*
 * EXT_INT_Config.h
 *
 *  Created on: ???/???/????
 *      Author: dell
 */

#ifndef MCAL_EXT_INT_EXT_INT_CONFIG_H_
#define MCAL_EXT_INT_EXT_INT_CONFIG_H_
/*
 * SELECT SENSE_CONTROL0 OPTIONTS : RISING_EDGE , FALLING_EDGE , LOW_LEVEL , ANY_LOGICAL_CHANGE
 */
#define SENSE_CONTROL0        RISING_EDGE
/*
 * SELECT SENSE_CONTROL1 OPTIONTS : RISING_EDGE , FALLING_EDGE , LOW_LEVEL , ANY_LOGICAL_CHANGE
 */
#define SENSE_CONTROL1        FALLING_EDGE
/*
 * SELECT SENSE_CONTROL2 OPTIONTS : RISING_EDGE , FALLING_EDGE , LOW_LEVEL , ANY_LOGICAL_CHANGE
 */
#define SENSE_CONTROL2        RISING_EDGE

#endif /* MCAL_EXT_INT_EXT_INT_CONFIG_H_ */
